gestor.activo=SQL_SERVER

sqlserver.url=jdbc:sqlserver://localhost:1433;databaseName=SistemaCompras;encrypt=true;trustServerCertificate=true
sqlserver.user=sa
sqlserver.password=root

mysql.url=jdbc:mysql://localhost:3306/SistemaCompras?useSSL=false&serverTimezone=UTC
mysql.user=root
mysql.password=TuPassword123